# Generated by Django 2.2.1 on 2019-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('disco', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('bios', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=50)),
                ('externo', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('usuario_equipos', models.CharField(max_length=50)),
            ],
        ),
    ]
